import os
import json
from anthropic import Anthropic
from dotenv import load_dotenv
from ics import Calendar, Event
import weasyprint
load_dotenv()

client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))

CALENDAR_TOOLS = [
    {
        "name": "add_events_to_calendar",
        "description": "Adds a list of schedule events to the calendar. Use this whenever the user provides activities to schedule.",
        "input_schema": {
            "type": "object",
            "properties": {
                "event_list": {
                    "type": "array",
                    "description": "List of events to add",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string", "description": "Name of the activity"},
                            "begin": {"type": "string", "description": "ISO 8601 timestamp (e.g., '2026-07-20T09:00:00')"},
                            "end": {"type": "string", "description": "ISO 8601 timestamp (e.g., '2026-07-20T10:00:00')"},
                            "description": {"type": "string", "description": "Optional details"}
                        },
                        "required": ["name", "begin", "end"]
                    }
                }
            },
            "required": ["event_list"]
        }
    }
]

def export_calendar_to_pdf(calendar, filename="my_schedule.pdf"):
    """
    Transforms the internal Calendar objects directly into a clean, 
    professionally stylized PDF document using an HTML/CSS template engine.
    """
    print(f"\n--- Generating '{filename}' ---")
    
    # Sort events chronologically by start time
    sorted_events = sorted(list(calendar.events), key=lambda x: x.begin)
    
    if not sorted_events:
        print("No events in calenda r to export!")
        return

    # Build dynamic HTML rows from our in-memory calendar 
    event_html_blocks = ""
    for event in sorted_events:
        # Format dates visually for clean reading
        time_display = f"{event.begin.strftime('%b %d, %Y | %I:%M %p')} - {event.end.strftime('%I:%M %p')}"
        desc_display = event.description if event.description else "No additional description provided."
        
        event_html_blocks += f"""
        <div class="event-card">
            <div class="event-time">{time_display}</div>
            <div class="event-title">{event.name}</div>
            <p class="event-desc">{desc_display}</p>
        </div>
        """

    html_document = f"""
    <html>
    <head>
    <style>
        @page {{
            size: A4;
            margin: 15mm;
            background-color: #f8fafc;
        }}
        body {{
            font-family: 'Helvetica Neue', Arial, sans-serif;
            color: #1e293b;
            margin: 0;
            padding: 0;
        }}
        .header {{
            background-color: #0f172a;
            color: white;
            padding: 24px;
            border-radius: 8px;
            margin-bottom: 24px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 20pt;
            font-weight: 600;
        }}
        .header p {{
            margin: 4px 0 0 0;
            color: #94a3b8;
            font-size: 11pt;
        }}
        .event-card {{
            background: white;
            padding: 16px;
            margin-bottom: 12px;
            border-radius: 6px;
            border-left: 4px solid #3b82f6;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            page-break-inside: avoid;
        }}
        .event-time {{
            font-weight: bold;
            color: #2563eb;
            font-size: 10pt;
            margin-bottom: 4px;
        }}
        .event-title {{
            font-size: 13pt;
            font-weight: 600;
            color: #0f172a;
            margin-bottom: 4px;
        }}
        .event-desc {{
            font-size: 10pt;
            color: #64748b;
            margin: 0;
        }}
    </style>
    </head>
    <body>
        <div class="header">
            <h1>Your Master Schedule</h1>
            <p>Organized and generated by Ethan</p>
        </div>
        {event_html_blocks}
    </body>
    </html>
    """
    
    temp_html_path = "temp_print_layout.html"
    with open(temp_html_path, "w", encoding="utf-8") as f:
        f.write(html_document)
        
    weasyprint.HTML(temp_html_path).write_pdf(filename)
    
    if os.path.exists(temp_html_path):
        os.remove(temp_html_path)
        
    print(f"Success! Saved document to {os.path.abspath(filename)}")
def run_chat():
    cal = Calendar()
    print('You: (type exit to quit)')
    system_message =  """
You are Ethan, a Calander and time managment organizer .

Your job is to take pre built activities and make them into a calander.

Rules:
- Always Be as orgenised as possible.
- Never let two activities overlap eachother.

Response format:
- Start with a one-sentence summary of what the user said.
- Then give your response.
- Countinue to next step or offer more.
CRITICAL: When processing events, you MUST call the add_events_to_calendar tool immediately.
"""
    history = []

    while True:
        user_input = input('>> ')

        if user_input.lower() == 'exit':
            break

        if user_input.lower() == 'pdf':
            export_calendar_to_pdf(cal)
            continue

        history.append({'role': 'user', 'content': user_input})

        response = client.messages.create(
            model='claude-haiku-4-5-20251001',
            max_tokens=600,
            temperature=0.0,
            system=system_message,
            tools = CALENDAR_TOOLS, 
            messages=history
        )
        for block in response.content:
            if block.type == 'text':
                print(f'Claude: {block.text}')
            elif block.type == 'tool_use':
                if block.name == 'add_events_to_calendar':
                    args = block.input
                    cal = add_events_to_calendar(cal, args['event_list'])
                    print(f"[System: Successfully added {len(args['event_list'])} event(s) to the calendar object.]")

        reply = response.content[0].text
        print(f'Claude: {reply}')
        history.append({'role': 'assistant', 'content': reply})


def add_events_to_calendar(calendar, event_list):
    """
    Adds a list of events directly to an in-memory Calendar object.
    
    :param calendar: An ics.Calendar instance
    :param event_list: List of dicts containing 'name', 'begin', and 'end'
    :return: The updated Calendar instance
    """
    
    for item in event_list:
        print("Run through function succecfully")
        print(f"Adding events: {event_list}\n")
        event = Event()
        event.name = item.get('name')
        event.begin = item.get('begin')
        event.end = item.get('end')

        if 'description' in item:
            event.description = item['description']
        calendar.events.add(event)
    return calendar

run_chat()