import os
import json
from anthropic import Anthropic
from dotenv import load_dotenv
from ics import Calendar, Event
import weasyprint
from datetime import datetime





load_dotenv()

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))


CALENDAR_TOOLS = [
    {
        "name": "read_workout_plan",
        "description": "Reads the workout plan generated by Agent 1 from workout_plan.json. Use this when the user asks to convert or schedule their workout plan.",
        "input_schema": {
            "type": "object",
            "properties": {}
        }
    },

    {
        "name": "add_events_to_calendar",
        "description": "Adds a list of schedule events to the calendar.",
        "input_schema": {
            "type": "object",
            "properties": {
                "event_list": {
                    "type": "array",
                    "description": "List of events to add",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Name of the activity"
                            },
                            "begin": {
                                "type": "string",
                                "description": "ISO 8601 start time"
                            },
                            "end": {
                                "type": "string",
                                "description": "ISO 8601 end time"
                            },
                            "description": {
                                "type": "string",
                                "description": "Extra details about the event"
                            }
                        },
                        "required": [
                            "name",
                            "begin",
                            "end"
                        ]
                    }
                }
            },
            "required": [
                "event_list"
            ]
        }
    }
]


def export_calendar_to_pdf(calendar, filename="my_schedule.pdf"):

    print(f"\n--- Generating {filename} ---")

    sorted_events = sorted(
        list(calendar.events),
        key=lambda x: x.begin
    )

    if not sorted_events:
        print("No events in calendar to export!")
        return


    event_html_blocks = ""

    for event in sorted_events:

        time_display = (
            f"{event.begin.strftime('%b %d, %Y | %I:%M %p')}"
            f" - {event.end.strftime('%I:%M %p')}"
        )

        description = (
            event.description
            if event.description
            else "No additional description provided."
        )


        event_html_blocks += f"""
        <div class="event-card">

            <div class="event-time">
                {time_display}
            </div>

            <div class="event-title">
                {event.name}
            </div>

            <p class="event-desc">
                {description}
            </p>

        </div>
        """


    html_document = f"""
    <html>

    <head>

    <style>

    @page {{
        size: A4;
        margin: 15mm;
        background-color: #f8fafc;
    }}


    body {{
        font-family: Arial, sans-serif;
        color: #1e293b;
    }}


    .header {{
        background-color: #0f172a;
        color: white;
        padding: 24px;
        border-radius: 8px;
        margin-bottom: 24px;
    }}


    .header h1 {{
        margin:0;
    }}


    .event-card {{
        background:white;
        padding:16px;
        margin-bottom:12px;
        border-radius:6px;
        border-left:4px solid #3b82f6;
    }}


    .event-time {{
        font-weight:bold;
        color:#2563eb;
    }}


    .event-title {{
        font-size:13pt;
        font-weight:bold;
        margin-top:5px;
    }}


    .event-desc {{
        color:#64748b;
    }}


    </style>

    </head>


    <body>

        <div class="header">

            <h1>
                Your Master Schedule
            </h1>

            <p>
                Organized and generated by Ethan
            </p>

        </div>


        {event_html_blocks}


    </body>

    </html>
    """


    temp_html_path = "temp_print_layout.html"


    with open(temp_html_path, "w", encoding="utf-8") as f:
        f.write(html_document)


    weasyprint.HTML(temp_html_path).write_pdf(filename)


    if os.path.exists(temp_html_path):
        os.remove(temp_html_path)


    print(
        f"Success! Saved document to {os.path.abspath(filename)}"
    )
def read_workout_plan():
    with open("workout_plan.json", "r") as f:
        return json.load(f)



def run_chat2():
    now = datetime.now()
    cal = Calendar()

    print("You: (type exit to quit)")

    system_message = f"""
You are Ethan, a calendar and time management organizer.

Your job is to take pre-built activities and turn them into a calendar.

Rules:
- Always be as organized as possible.
- If the user asks you to schedule or convert a workout plan, FIRST call the read_workout_plan tool.
- After receiving the workout plan, immediately call add_events_to_calendar.
- If you receive days without a specific date, assume the closest possible date, know the date with now the veriable.

# Fetch current local date and time
now = datetime.now()

print("Full timestamp:", now)
print("Year:", now.year)
print("Month:", now.month)
print("Day:", now.day)

- Never allow two activities to overlap.

Response format:
- Start with one sentence summarizing what the user said.
- Then give your response.

IMPORTANT:
When processing a workout plan, you MUST use the tools.

Todays date is {now}
"""


    history = []


    while True:

        user_input = input(">> ")


        if user_input.lower() == "exit":
            break


        if user_input.lower() == "pdf":

            export_calendar_to_pdf(cal)

            continue



        history.append(
            {
                "role": "user",
                "content": user_input
            }
        )



        while True:

               
            response = client.messages.create(

                model="claude-haiku-4-5-20251001",

                max_tokens=600,

                temperature=0.0,

                system=system_message,

                tools=CALENDAR_TOOLS,

                messages=history

            )



            tool_used = False



            for block in response.content:



                if block.type == "text":

                    print(f"Claude: {block.text}")



                elif block.type == "tool_use":


                    tool_used = True



                    # TOOL 1: READ WORKOUT PLAN

                    if block.name == "read_workout_plan":


                        workout = read_workout_plan()



                        history.append(
                            {
                                "role": "assistant",
                                "content": response.content
                            }
                        )



                        history.append(
                            {
                                "role": "user",
                                "content": [
                                    {
                                        "type": "tool_result",

                                        "tool_use_id": block.id,

                                        "content": json.dumps(workout)
                                    }
                                ]
                            }
                        )



                    
                    # TOOL 2: ADD EVENTS
                   

                    elif block.name == "add_events_to_calendar":


                        args = block.input



                        cal = add_events_to_calendar(
                            cal,
                            args["event_list"]
                        )



                        print(
                            f"[System: Successfully added {len(args['event_list'])} event(s) to calendar]"
                        )



                        history.append(
                            {
                                "role": "assistant",
                                "content": response.content
                            }
                        )



                        history.append(
                            {
                                "role": "user",

                                "content": [
                                    {
                                        "type": "tool_result",

                                        "tool_use_id": block.id,

                                        "content": "Calendar updated successfully."
                                    }
                                ]
                            }
                        )



            # If Claude used a tool,
            # call Claude again so it can continue

            if tool_used:

                continue


            else:

                history.append(
                    {
                        "role": "assistant",

                        "content": response.content
                    }
                )

                break
def add_events_to_calendar(calendar, event_list):
    """
    Adds a list of events directly to an in-memory Calendar object.

    :param calendar: An ics.Calendar instance
    :param event_list: List of dicts containing 'name', 'begin', and 'end'
    :return: Updated Calendar instance
    """

    for item in event_list:

        print("Running add_events_to_calendar()")
        print(f"Adding event: {item}")

        event = Event()

        event.name = item["name"]
        event.begin = item["begin"]
        event.end = item["end"]

        if "description" in item:
            event.description = item["description"]

        calendar.events.add(event)

    return calendar


run_chat2()